# Generated by Django 3.2.6 on 2022-04-15 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=16)),
                ('self_photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=800)),
                ('title', models.CharField(max_length=60)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=120)),
                ('example', models.URLField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FiveWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.TextField(max_length=400)),
                ('started', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('purpose', models.TextField(max_length=400)),
                ('how_its_done', models.TextField(max_length=400)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FactsForFiveWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_score', models.IntegerField(choices=[(0, 'Low'), (1, 'Med'), (2, 'High')])),
                ('factoid', models.TextField(max_length=120)),
                ('five_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.fivews')),
            ],
        ),
    ]
